variable "location" {}
variable "env" {}
variable "code" {}
variable "cidr" {}
variable "rg_name" {}
variable "s_pri_id" {}
variable "vm_size" {}
variable "vm_login_username" {}
variable "vm_login_password" {}
variable "vm_img_publisher" {}
variable "vm_img_offer" {}
variable "vm_img_sku" {}
variable "vm_img_version" {}
