variable "location" {}
variable "env" {}
variable "code" {}
variable "cidr" {}
variable "rg_name" {}
variable "s_pri_id" {}
variable "vm_win_size" {}
variable "vm_win_login_username" {}
variable "vm_win_login_password" {}
variable "vm_win_img_publisher" {}
variable "vm_win_img_offer" {}
variable "vm_win_img_sku" {}
variable "vm_win_img_version" {}
